#!/usr/bin/python
import subprocess


def color(text, name: str):
    end = '\033[0m'
    clr = dict(
        HEADER = '\033[95m',
        OKBLUE = '\033[94m',
        OKGREEN = '\033[92m',
        WARNING = '\033[93m',
        FAIL = '\033[91m',
        BOLD = '\033[1m',
        UNDERLINE = '\033[4m',
    )[name.upper()]
    return "{}{}{}".format(clr, text, end)

def cmd(cmd, *args):
    cmd = "kubectl {}".format(cmd.format(*args))
    out = subprocess.check_output(cmd, shell=True).decode("utf-8").split("\n")
    return [item for item in out if item]

def prompt(content):
    print(color(color("   {}".format(content.pop(0)), "underline"), "okblue"))
    for index, item in enumerate(content):
        print(color("{}. {}".format(index, item), "okblue"))
        
    def choice():
        print()
        val = input(color("Select option (only numbers): ", "bold"))
        if val.isdigit() and int(val) < len(content):
            return int(val)
        return choice()


    value = choice()
    return tuple(content[value].split())

def main():
    contexts = cmd("config get-contexts")
    curr, name, cluster, authinfo, namespace = prompt(contexts)
    out = cmd("config use-context {}".format(name))
    print(color("\n".join(out), "okgreen"))

if __name__ == "__main__":
    main()